stages:
  - test12
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  IMAGE_MCVQOE_BASE: "This has priority!"

image: python:3.8

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - source venv/bin/activate

test12:
  stage: test12
  script:
    - echo $IMAGE_MCVQOE_BASE

build:
  stage: build
  before_script:
    - python -V
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install git+https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.nist.gov/PSCR/MCV/mcv-qoe-library.git
    - pip install .

test-measure_class:
  stage: test
  script:
    - python tests/test_measure_class.py

